"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, BadgeCheck, Banknote, Building2, Check, ChevronDown, CircleDollarSign, CreditCard, Landmark, LockKeyhole, MapPin, PackageCheck, ShieldCheck, Smartphone, Truck, WalletCards } from "lucide-react";
import { useStore } from "@/components/store-provider";
import { formatPrice } from "@/lib/catalog";

const paymentMethods = [
  { id: "upi", name: "UPI", note: "Google Pay, PhonePe, Paytm", icon: Smartphone },
  { id: "card", name: "Credit / Debit card", note: "Visa, Mastercard, RuPay, Amex", icon: CreditCard },
  { id: "netbanking", name: "Net banking", note: "All major Indian banks", icon: Landmark },
  { id: "wallet", name: "Wallets", note: "Luma Wallet and partner wallets", icon: WalletCards },
  { id: "cod", name: "Cash on delivery", note: "Pay when your order arrives", icon: Banknote },
  { id: "emi", name: "EMI / Pay later", note: "Flexible plans from ₹630/month", icon: CircleDollarSign },
];

export default function CheckoutPage() {
  const { cart, cartTotal } = useStore();
  const [address, setAddress] = useState<"saved" | "new">("saved");
  const [shipping, setShipping] = useState("express");
  const [payment, setPayment] = useState("upi");
  const [placed, setPlaced] = useState(false);

  if (placed) return <main className="order-success shell"><div className="success-icon"><Check /></div><p className="eyebrow">Order confirmed</p><h1>Thank you, Ananya!</h1><p>Your order <strong>#LU2605261048</strong> has been placed. We&apos;ve sent confirmation and tracking details to your email.</p><div className="success-delivery"><Truck /><span><small>Estimated delivery</small><strong>Tomorrow, 10 AM – 2 PM</strong></span></div><div className="success-actions"><Link href="/account?tab=orders" className="primary-button">Track my order</Link><Link href="/shop" className="secondary-button">Continue shopping</Link></div></main>;
  if (!cart.length) return <main className="order-success shell"><PackageCheck /><h1>Your bag is empty</h1><p>Add something remarkable before checking out.</p><Link href="/shop" className="primary-button">Browse products</Link></main>;

  return <main className="checkout-page shell"><nav className="checkout-nav"><Link href="/cart"><ArrowLeft /> Back to bag</Link><span className="logo">LUMA<i>.</i></span><p><LockKeyhole /> Secure checkout</p></nav><div className="checkout-progress"><span className="done"><i><Check /></i>Bag</span><b /><span className="active"><i>2</i>Delivery</span><b /><span><i>3</i>Payment</span></div>
    <div className="checkout-layout"><div className="checkout-forms"><section className="checkout-card"><header><span>1</span><div><h2>Contact details</h2><p>We&apos;ll send order updates here</p></div><button>Sign in instead</button></header><div className="form-grid"><label>Email address<input defaultValue="ananya@example.com" type="email" required /></label><label>Mobile number<div className="phone-input"><span>+91</span><input defaultValue="98765 43210" /></div></label></div><label className="check-label"><input type="checkbox" defaultChecked /> Send order updates on WhatsApp</label></section>
      <section className="checkout-card"><header><span>2</span><div><h2>Delivery address</h2><p>Where should we send your order?</p></div></header><div className="address-tabs"><button className={address === "saved" ? "active" : ""} onClick={() => setAddress("saved")}><MapPin /> Saved address</button><button className={address === "new" ? "active" : ""} onClick={() => setAddress("new")}><Building2 /> Add new address</button></div>{address === "saved" ? <div className="saved-address"><i><Check /></i><div><span><strong>Ananya Kapoor</strong><em>HOME</em></span><p>42, Sea View Apartments, Carter Road<br />Bandra West, Mumbai, Maharashtra 400050</p><small>+91 98765 43210</small></div><button>Edit</button></div> : <div className="address-form form-grid"><label>Full name<input placeholder="Recipient name" /></label><label>Phone<input placeholder="10-digit number" /></label><label className="wide">Address<input placeholder="House number, building and street" /></label><label>City<input placeholder="City" /></label><label>Postal code<input placeholder="6-digit pincode" /></label></div>}</section>
      <section className="checkout-card"><header><span>3</span><div><h2>Delivery method</h2><p>Choose how quickly it arrives</p></div></header><div className="shipping-options"><label className={shipping === "express" ? "active" : ""}><input type="radio" checked={shipping === "express"} onChange={() => setShipping("express")} /><i>{shipping === "express" && <Check />}</i><Truck /><span><strong>Express delivery</strong><small>Tomorrow, 10 AM – 2 PM</small></span><b>FREE</b></label><label className={shipping === "standard" ? "active" : ""}><input type="radio" checked={shipping === "standard"} onChange={() => setShipping("standard")} /><i>{shipping === "standard" && <Check />}</i><PackageCheck /><span><strong>Standard delivery</strong><small>In 2–4 business days</small></span><b>FREE</b></label></div></section>
      <section className="checkout-card payment-card"><header><span>4</span><div><h2>Payment</h2><p>All transactions are secure and encrypted</p></div><LockKeyhole /></header><div className="payment-layout"><nav>{paymentMethods.map((method) => { const Icon = method.icon; return <button className={payment === method.id ? "active" : ""} onClick={() => setPayment(method.id)} key={method.id}><Icon /><span><strong>{method.name}</strong><small>{method.note}</small></span></button>; })}</nav><div className="payment-fields">{payment === "upi" && <><h3>Pay with UPI</h3><label>UPI ID<div><input placeholder="yourname@bank" /><button>Verify</button></div></label><p>Or pay instantly with</p><div className="payment-apps"><button>G Pay</button><button>PhonePe</button><button>Paytm</button></div></>}{payment === "card" && <><h3>Card details</h3><label>Card number<input placeholder="1234 5678 9012 3456" /></label><div className="form-grid"><label>Expiry<input placeholder="MM / YY" /></label><label>CVV<input placeholder="•••" /></label></div><label className="check-label"><input type="checkbox" /> Save securely for future purchases</label></>}{!['upi','card'].includes(payment) && <div className="payment-placeholder"><BadgeCheck /><h3>{paymentMethods.find((item) => item.id === payment)?.name}</h3><p>This secure payment option is available for your order. You&apos;ll confirm on the next step.</p></div>}</div></div></section><label className="order-notes">Order notes (optional)<textarea placeholder="Delivery instructions or a note for the seller" /></label></div>
      <aside className="checkout-summary"><div className="checkout-summary-card"><h2>Your order <Link href="/cart">Edit bag</Link></h2><div className="checkout-products">{cart.map((line) => <div key={line.product.id}><span><img src={line.product.image} alt={line.product.name} /><b>{line.quantity}</b></span><p><strong>{line.product.name}</strong><small>{line.size} · Qty {line.quantity}</small></p><em>{formatPrice(line.product.price * line.quantity)}</em></div>)}</div><div className="summary-lines"><p><span>Subtotal</span><strong>{formatPrice(cartTotal)}</strong></p><p><span>Shipping</span><strong className="green">FREE</strong></p><p><span>Tax</span><strong>Included</strong></p><p><span>Rewards earned</span><strong className="green">+{Math.round(cartTotal / 100)} pts</strong></p></div><div className="summary-total"><span><strong>Order total</strong><small>Inclusive of all taxes</small></span><strong>{formatPrice(cartTotal)}</strong></div><button className="place-order" onClick={() => setPlaced(true)}>Pay {formatPrice(cartTotal)} securely <LockKeyhole /></button><p className="terms">By placing this order, you agree to Luma&apos;s Terms of Use and Privacy Policy.</p></div><div className="checkout-trust"><ShieldCheck /><p><strong>Luma purchase protection</strong><span>Authentic products · Secure payment · Easy returns</span></p></div><button className="currency-select">₹ INR · India <ChevronDown /></button></aside></div>
  </main>;
}
