"use client";

import { useState } from "react";
import Link from "next/link";
import { Activity, Bell, Box, ChevronDown, ChevronRight, CircleDollarSign, FileText, Gauge, Grid2X2, Image, LayoutDashboard, Menu, Package, Plus, Search, Settings, ShoppingBag, Star, Store, Tag, TrendingDown, TrendingUp, Truck, UserCog, Users, Warehouse, X } from "lucide-react";
import { formatPrice, products } from "@/lib/catalog";

const adminNav = [
  [LayoutDashboard,"Dashboard"],[ShoppingBag,"Orders"],[Box,"Products"],[Grid2X2,"Categories"],[Store,"Brands & sellers"],[Users,"Customers"],[Tag,"Coupons & offers"],[Image,"Banners & CMS"],[Warehouse,"Inventory"],[Truck,"Shipping"],[Star,"Review moderation"],[FileText,"Returns & refunds"],[Bell,"Notifications"],[Activity,"Analytics"],[UserCog,"Roles & access"],[Settings,"Settings"],
] as const;

export default function AdminPage() {
  const [section, setSection] = useState("Dashboard");
  const [mobileNav, setMobileNav] = useState(false);
  return <main className="portal admin-portal"><aside className={mobileNav ? "open" : ""}><div className="portal-logo"><Link className="logo logo-light" href="/">LUMA<span>.</span></Link><em>ADMIN</em><button onClick={() => setMobileNav(false)}><X /></button></div><div className="admin-profile"><span>AK</span><p><strong>Ananya Kapoor</strong><small>Super administrator</small></p><ChevronDown /></div><nav>{adminNav.map(([Icon,label],index) => <button key={label} onClick={() => {setSection(label);setMobileNav(false);}} className={section === label ? "active" : ""}><Icon />{label}{[1,10,11].includes(index) && <em>{index === 1 ? "28" : index === 10 ? "12" : "7"}</em>}</button>)}</nav><div className="portal-version">Luma Console · v2.6.1</div></aside><section className="portal-main"><header className="portal-topbar"><button className="portal-menu" onClick={() => setMobileNav(true)}><Menu /></button><div><h1>{section}</h1><p>Monday, 26 May 2026</p></div><label><Search /><input placeholder="Search orders, products, customers…" /></label><button><Bell /><b>5</b></button><button><CircleDollarSign /> INR <ChevronDown /></button></header>
    {section !== "Dashboard" ? <AdminModule title={section} /> : <div className="portal-content"><div className="portal-heading"><div><p className="eyebrow">Live overview</p><h2>Here&apos;s what&apos;s happening today.</h2></div><div><button className="secondary-button">Download report</button><button className="primary-button"><Plus /> Add product</button></div></div><div className="admin-stats">{[["Gross revenue","₹28.4L","+12.8%",TrendingUp],["Orders","1,842","+8.2%",ShoppingBag],["Customers","14,286","+18.6%",Users],["Conversion rate","4.82%","−0.4%",Gauge]].map(([label,value,trend,Icon]) => { const I = Icon as typeof TrendingUp; return <article key={String(label)}><header><span><I /></span><small>vs last month</small></header><p>{String(label)}</p><strong>{String(value)}</strong><em className={String(trend).startsWith("−") ? "down" : ""}>{String(trend).startsWith("−") ? <TrendingDown /> : <TrendingUp />}{String(trend)}</em></article>; })}</div>
      <div className="admin-grid"><section className="revenue-chart portal-card"><header><div><h3>Revenue overview</h3><p>Gross sales across all channels</p></div><select><option>Last 7 months</option></select></header><div className="chart-summary"><span><small>TOTAL REVENUE</small><strong>₹1.82 Cr</strong></span><span><i /> This year</span><span><i /> Last year</span></div><div className="bar-chart">{[42,58,49,68,63,84,76,92,70,96,88,100].map((height,index) => <div key={index}><span style={{height:`${Math.max(25,height-19)}%`}}/><b style={{height:`${height}%`}}/><small>{["Jun","Jul","Aug","Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May"][index]}</small></div>)}</div></section><section className="sales-channel portal-card"><header><h3>Sales by channel</h3><button>•••</button></header><div className="donut"><div><strong>₹28.4L</strong><small>Total</small></div></div><ul><li><i />Luma web <strong>64%</strong></li><li><i />Mobile app <strong>28%</strong></li><li><i />Marketplace <strong>8%</strong></li></ul></section></div>
      <div className="admin-grid lower"><section className="recent-orders portal-card"><header><div><h3>Recent orders</h3><p>Latest customer transactions</p></div><button>View all <ChevronRight /></button></header><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th><th>Payment</th></tr></thead><tbody>{[["#LU10482","Meera Nair","Processing","₹12,999","UPI"],["#LU10481","Rohan Shah","Shipped","₹5,299","Card"],["#LU10480","Priya Mehta","Delivered","₹18,999","EMI"],["#LU10479","Arjun Rao","Return","₹2,799","COD"]].map((row) => <tr key={row[0]}><td><strong>{row[0]}</strong><small>2 min ago</small></td><td>{row[1]}</td><td><span className={`status-${row[2].toLowerCase()}`}>{row[2]}</span></td><td><strong>{row[3]}</strong></td><td>{row[4]}</td></tr>)}</tbody></table></section><section className="low-stock portal-card"><header><div><h3>Low stock alerts</h3><p>8 products need attention</p></div><button>View inventory</button></header>{products.slice(0,4).map((product,index) => <div key={product.id}><img src={product.image} alt={product.name}/><p><strong>{product.name}</strong><small>SKU · LU-{product.id.toUpperCase()}-01</small></p><span><strong>{[3,5,7,9][index]}</strong><small>left</small></span></div>)}</section></div>
      <section className="admin-insights"><SparkCard icon={TrendingUp} title="AI commerce insight" copy="Headphones are trending 34% above forecast. Consider raising Aura Pro safety stock at Mumbai warehouse." action="Review forecast"/><SparkCard icon={Activity} title="Conversion opportunity" copy="Cart recovery campaigns generated ₹3.2L this week, up 18% from your previous sequence." action="View campaign"/></section>
    </div>}
  </section></main>;
}
function SparkCard({icon:Icon,title,copy,action}:{icon:typeof TrendingUp;title:string;copy:string;action:string}) { return <article><span><Icon /></span><p><strong>{title}</strong><small>{copy}</small></p><button>{action} <ChevronRight /></button></article>; }
function AdminModule({title}:{title:string}) { return <div className="portal-content"><div className="portal-heading"><div><p className="eyebrow">Management</p><h2>{title}</h2><p>Search, filter and manage marketplace {title.toLowerCase()} from one secure workspace.</p></div><button className="primary-button"><Plus /> Create new</button></div><section className="module-placeholder portal-card"><span><Settings /></span><h3>{title} workspace</h3><p>Advanced controls, bulk actions, approval workflows, audit history and export tools are available for authorized roles.</p><div><button className="secondary-button">Import CSV</button><button className="primary-button">Open {title.toLowerCase()}</button></div></section></div>; }
